version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: book-tp-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
