spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookdb
    username: bookuser
    password: bookpass
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog.xml
